/*
 * Generated by MTK Easy PinMux Tool Version 2.1.0 for 7686D. Copyright MediaTek Inc. (C) 2015.
 * 2017-01-20 15:51:57:0794
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char HAL_UART1_RXD_PIN = 2;
const char HAL_UART1_RXD_PIN_M_GPIO = 0;
const char HAL_UART1_RXD_PIN_M_EINT = 1;
const char HAL_UART1_RXD_PIN_M_WIFIRF_DBGOUT2 = 2;
const char HAL_UART1_RXD_PIN_M_URXD1 = 3;
const char HAL_UART1_RXD_PIN_M_PWM0 = 4;
const char HAL_UART1_RXD_PIN_M_I2S_WS = 5;
const char HAL_UART1_RXD_PIN_M_JTCK = 6;
const char HAL_UART1_RXD_PIN_M_CLKO = 7;
const char HAL_UART1_RXD_PIN_M_WF_JTCK = 8;
const char HAL_UART1_RXD_PIN_M_BT_PRI0 = 9;
const char HAL_UART1_RXD_PIN_M_WIFI_ANT_SEL4 = 10;


const char HAL_UART1_TXD_PIN = 3;
const char HAL_UART1_TXD_PIN_M_GPIO = 0;
const char HAL_UART1_TXD_PIN_M_EINT = 1;
const char HAL_UART1_TXD_PIN_M_WIFIRF_DBGOUT3 = 2;
const char HAL_UART1_TXD_PIN_M_UTXD1 = 3;
const char HAL_UART1_TXD_PIN_M_PWM1 = 4;
const char HAL_UART1_TXD_PIN_M_I2S_CK = 5;
const char HAL_UART1_TXD_PIN_M_JTRST_B = 6;
const char HAL_UART1_TXD_PIN_M_DEBUGMON0 = 7;
const char HAL_UART1_TXD_PIN_M_WF_JTRST_B = 8;
const char HAL_UART1_TXD_PIN_M_WIFI_ANT_SEL2 = 9;

const char HAL_UART0_RXD_PIN = 19;
const char HAL_UART0_RXD_PIN_M_GPIO = 0;
const char HAL_UART0_RXD_PIN_M_URXD0 = 1;
const char HAL_UART0_RXD_PIN_M_EINT = 2;
const char HAL_UART0_RXD_PIN_M_SCL1 = 3;
const char HAL_UART0_RXD_PIN_M_PWM5 = 5;
const char HAL_UART0_RXD_PIN_M_AUXADC2 = 6;
const char HAL_UART0_RXD_PIN_M_WIFI_EXT_CLK = 7;


const char HAL_UART0_TXD_PIN = 20;
const char HAL_UART0_TXD_PIN_M_GPIO = 0;
const char HAL_UART0_TXD_PIN_M_UTXD0 = 1;
const char HAL_UART0_TXD_PIN_M_EINT = 2;
const char HAL_UART0_TXD_PIN_M_AUXADC3 = 6;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_UART0_DTE_DCD_PIN = 0xff;
const char HAL_UART0_DTE_DSR_PIN = 0xff;
const char HAL_UART0_DTE_DTR_PIN = 0xff;
const char HAL_UART0_DTE_RI_PIN = 0xff;
const char HAL_UART1_DTE_DCD_PIN = 0xff;
const char HAL_UART1_DTE_DSR_PIN = 0xff;
const char HAL_UART1_DTE_DTR_PIN = 0xff;
const char HAL_UART1_DTE_RI_PIN = 0xff;
const char HAL_UART2_DTE_DCD_PIN = 0xff;
const char HAL_UART2_DTE_DSR_PIN = 0xff;
const char HAL_UART2_DTE_DTR_PIN = 0xff;
const char HAL_UART2_DTE_RI_PIN = 0xff;
const char BSP_CTP_SW_I2C_SCL_PIN = 0xff;
const char BSP_CTP_SW_I2C_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_GNSS_POWER_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_32K_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_WIFI_RESET_PIN = 0xff;
const char BSP_WIFI_ENABLE_PIN = 0xff;
const char BSP_HP_ANA_SW_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;
const char EXT_NTC_POWER_SW_PIN = 0xff;
const char EXT_NTC_ADC_PIN = 0xff;
const char EXT_DSP_POWER_SW_PIN = 0xff;
const char EXT_DSP_CLK_SW_PIN = 0xff;
const char EXT_DSP_RTC_CLK_SW_PIN = 0xff;
const char EXT_DSP_32K_CLK_PIN = 0xff;
const char NOTIFY_EXT_DSP_IRQ_PIN = 0xff;
const char BSP_LED0_PIN = 0xff;
const char BSP_LED1_PIN = 0xff;
const char BSP_LED2_PIN = 0xff;
const char BSP_EINTKEY0_PIN = 0xff;
const char BSP_EINTKEY1_PIN = 0xff;
const char BSP_EINTKEY2_PIN = 0xff;


const char HAL_I2C_MASTER_0_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_0_SDA_PIN = 0xff;
const char HAL_I2C_MASTER_1_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_1_SDA_PIN = 0xff;
const char HAL_AUXADC_0_PIN = 0xff;
const char HAL_AUXADC_1_PIN = 0xff;
const char HAL_AUXADC_2_PIN = 0xff;
const char HAL_AUXADC_3_PIN = 0xff;
const char HAL_MSDC_0_CK_PIN = 0xff;
const char HAL_MSDC_0_CM_PIN = 0xff;
const char HAL_MSDC_0_DA0_PIN = 0xff;
const char HAL_MSDC_0_DA1_PIN = 0xff;
const char HAL_MSDC_0_DA2_PIN = 0xff;
const char HAL_MSDC_0_DA3_PIN = 0xff;
const char HAL_SDIO_SLV_CK_PIN = 0xff;
const char HAL_SDIO_SLV_CM_PIN = 0xff;
const char HAL_SDIO_SLV_DA0_PIN = 0xff;
const char HAL_SDIO_SLV_DA1_PIN = 0xff;
const char HAL_SDIO_SLV_DA2_PIN = 0xff;
const char HAL_SDIO_SLV_DA3_PIN = 0xff;
const char HAL_PWM_0_PIN = 0xff;
const char HAL_PWM_1_PIN = 0xff;
const char HAL_PWM_2_PIN = 0xff;
const char HAL_PWM_3_PIN = 0xff;
const char HAL_PWM_4_PIN = 0xff;
const char HAL_PWM_5_PIN = 0xff;
const char HAL_UART0_CTS_PIN = 0xff;
const char HAL_UART0_RTS_PIN = 0xff;
const char HAL_UART1_CTS_PIN = 0xff;
const char HAL_UART1_RTS_PIN = 0xff;
const char HAL_UART2_TXD_PIN = 0xff;
const char HAL_UART2_RXD_PIN = 0xff;
const char HAL_UART2_CTS_PIN = 0xff;
const char HAL_UART2_RTS_PIN = 0xff;
const char HAL_SPI_MASTER_A_CS_PIN = 0xff;
const char HAL_SPI_MASTER_A_SCK_PIN = 0xff;
const char HAL_SPI_MASTER_A_SIO0_PIN = 0xff;
const char HAL_SPI_MASTER_A_SIO1_PIN = 0xff;
const char HAL_SPI_MASTER_A_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER_A_SIO3_PIN = 0xff;
const char HAL_SPI_SLV_A_CS_PIN = 0xff;
const char HAL_SPI_SLV_A_SCK_PIN = 0xff;
const char HAL_SPI_SLV_A_SIO0_PIN = 0xff;
const char HAL_SPI_SLV_A_SIO1_PIN = 0xff;
const char HAL_SPI_SLV_A_SIO2_PIN = 0xff;
const char HAL_SPI_SLV_A_SIO3_PIN = 0xff;
const char HAL_SPI_MASTER_B_CS_PIN = 0xff;
const char HAL_SPI_MASTER_B_SCK_PIN = 0xff;
const char HAL_SPI_MASTER_B_SIO0_PIN = 0xff;
const char HAL_SPI_MASTER_B_SIO1_PIN = 0xff;
const char HAL_SPI_MASTER_B_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER_B_SIO3_PIN = 0xff;
const char HAL_SPI_SLV_B_CS_PIN = 0xff;
const char HAL_SPI_SLV_B_SCK_PIN = 0xff;
const char HAL_SPI_SLV_B_SIO0_PIN = 0xff;
const char HAL_SPI_SLV_B_SIO1_PIN = 0xff;
const char HAL_SPI_SLV_B_SIO2_PIN = 0xff;
const char HAL_SPI_SLV_B_SIO3_PIN = 0xff;
const char HAL_I2S_MASTER_EDIDO_PIN = 0xff;
const char HAL_I2S_MASTER_EDIDI_PIN = 0xff;
const char HAL_I2S_MASTER_EDIWS_PIN = 0xff;
const char HAL_I2S_MASTER_EDICK_PIN = 0xff;
const char HAL_I2S1_MCLK_PIN = 0xff;
const char HAL_I2S1_BCLK_PIN = 0xff;
const char HAL_I2S1_WS_PIN = 0xff;
const char HAL_I2S1_TX_PIN = 0xff;
const char HAL_I2S1_RX_PIN = 0xff;
const char HAL_I2S0_MCLK_PIN = 0xff;
const char HAL_I2S0_BCLK_PIN = 0xff;
const char HAL_I2S0_WS_PIN = 0xff;
const char HAL_I2S0_TX_PIN = 0xff;
const char HAL_I2S0_RX_PIN = 0xff;



